apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: album-microservice
  labels:
    app: album
spec:
  replicas: 1
  selector:
    matchLabels:
      app: album
  template:
    metadata:
      labels:
        app: album
    spec:
      containers:
        - name: album-microservice
          image: gcr.io/ultimate-team-scalable/album-microservice
          env:
            - name: RABBIT_MQ_PORT
              value: "5672"
            - name: RABBIT_MQ_USER
              value: "user"
            - name: RABBIT_MQ_PASSWORD
              value: "user"
            - name: privateKey
              value: "14fc1631431bf690be27e5610869f85a14fc1631431bf690be27e5610869f85a14fc1631431bf690be27e5610869f85a"
            - name: ENV_TYPE
              value: "Deployment"
            - name: NUM_THREADS
              value: "3"
            - name: db_initial_pool_size
              value: "3"
            - name: db_max_pool_size
              value: "5"
            - name: MESSAGE_PREFETCH_COUNT
              value: "100"
            - name: nosqldb_port
              value: "8529"
            - name: nosqldb_name
              value: "ULTIMATE_TEAM"
            - name: db_driver
              value: "org.postgresql.Driver"
            - name: db_user
              value: "postgres"
            - name: db_password
              value: ""
            - name: CLASS_PREFIX
              value: "album_microservice."
            - name: COMMANDS
              value: '{"/albums/create": "CreateAlbum","/albums/favorite": "FavoriteAlbum","/albums/unfavorite": "UnFavoriteAlbum","/albums/delete": "DeleteAlbum","/albums/addpost": "AddPost","/albums/deletepost": "DeletePost","/albums/view": "ViewAlbum", "/albums/viewposts": "ViewPosts","/albums/viewfavoritealbums": "SearchFavorite"}'
          args:
            - bash
            - -c
            - sleep 20; java -jar /flickr/album/target/album-0.0.1-SNAPSHOT-jar-with-dependencies.jar;
          ports:
            - containerPort: 6384
          imagePullPolicy: Always
      restartPolicy: Always
