apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: conversation-microservice
  labels:
    app: conversation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversation
  template:
    metadata:
      labels:
        app: conversation
    spec:
      containers:
        - name: conversation-microservice
          image: gcr.io/ultimate-team-scalable/conversation-microservice
          env:
            - name: RABBIT_MQ_PORT
              value: "5672"
            - name: RABBIT_MQ_USER
              value: "user"
            - name: RABBIT_MQ_PASSWORD
              value: "user"
            - name: privateKey
              value: "14fc1631431bf690be27e5610869f85a14fc1631431bf690be27e5610869f85a14fc1631431bf690be27e5610869f85a"
            - name: ENV_TYPE
              value: "Deployment"
            - name: NUM_THREADS
              value: "3"
            - name: db_initial_pool_size
              value: "3"
            - name: db_max_pool_size
              value: "5"
            - name: MESSAGE_PREFETCH_COUNT
              value: "100"
            - name: nosqldb_port
              value: "8529"
            - name: nosqldb_name
              value: "ULTIMATE_TEAM"
            - name: db_driver
              value: "org.postgresql.Driver"
            - name: db_user
              value: "postgres"
            - name: db_password
              value: ""
            - name: CLASS_PREFIX
              value: "conversations_microservice."
            - name: COMMANDS
              value: '{"/conversations/create": "CreateConversation", "/conversations/message/create": "MessageUser", "/conversations/messages/get": "GetConversationMessages", "/conversation/get": "GetConversation"}'
          args:
            - bash
            - -c
            - sleep 20; java -jar /flickr/conversation/target/conversation-0.0.1-SNAPSHOT-jar-with-dependencies.jar;
          ports:
            - containerPort: 6386
          imagePullPolicy: Always
      restartPolicy: Always
