apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: http-server
  labels:
    app: http
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
        - name: http-server
          image: ameniawy/ultimate-team-http
          env:
            - name: RABBIT_MQ_PORT
              value: "5672"
            - name: RABBIT_MQ_USER
              value: "user"
            - name: RABBIT_MQ_PASSWORD
              value: "user"
            - name: ENV_TYPE
              value: "Deployment"
            - name: NUM_THREADS
              value: "3"
            - name: db_initial_pool_size
              value: "10"
            - name: db_max_pool_size
              value: "20"
            - name: nosqldb_port
              value: "5829"
            - name: nosqldb_name
              value: "ULTIMATE_TEAM"
          args:
            - /bin/sh
            - -c
            - sleep 20; java -jar http-0.0.1-SNAPSHOT-jar-with-dependencies.jar;
          ports:
            - containerPort: 6380
          imagePullPolicy: Always
      restartPolicy: Always
