apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: http-server
  labels:
    app: http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
        - name: http-server
          image: ameniawy/ultimate-team-http
          env:
            - name: RABBIT_MQ_PORT
              value: "15672"
            - name: RABBIT_MQ_USER
              value: "guest"
            - name: RABBIT_MQ_PASSWORD
              value: "guest"
          args:
            - /bin/sh
            - -c
            - sleep 10; java -jar http-0.0.1-SNAPSHOT-jar-with-dependencies.jar;
          ports:
            - containerPort: 6380
          imagePullPolicy: Always
      restartPolicy: Always
