apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: post-microservice
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post-microservice
          image: gcr.io/ultimate-team-scalable/post-microservice
          env:
            - name: RABBIT_MQ_PORT
              value: "5672"
            - name: RABBIT_MQ_USER
              value: "user"
            - name: RABBIT_MQ_PASSWORD
              value: "user"
            - name: privateKey
              value: "14fc1631431bf690be27e5610869f85a14fc1631431bf690be27e5610869f85a14fc1631431bf690be27e5610869f85a"
            - name: ENV_TYPE
              value: "Deployment"
            - name: NUM_THREADS
              value: "3"
            - name: db_initial_pool_size
              value: "3"
            - name: db_max_pool_size
              value: "5"
            - name: MESSAGE_PREFETCH_COUNT
              value: "100"
            - name: nosqldb_port
              value: "8529"
            - name: nosqldb_name
              value: "ULTIMATE_TEAM"
            - name: db_driver
              value: "org.postgresql.Driver"
            - name: db_user
              value: "postgres"
            - name: db_password
              value: ""
            - name: CLASS_PREFIX
              value: "posts_microservice."
            - name: COMMANDS
              value: '{"/posts/create": "Create", "/posts/view": "View","/posts/like": "Like","/posts/delete": "Delete","/posts/search": "Search","/posts/count": "Count","/posts/hashtag": "AddHashtag", "/posts/hashtag/delete":"RemoveHashtag","/posts/recent":"ViewRecent","/posts/favorited":"ViewFavorited","/posts/favorite":"Favorite","/posts/report":"Report"}'
          args:
            - bash
            - -c
            - sleep 20; java -jar /flickr/post/target/post-0.0.1-SNAPSHOT-jar-with-dependencies.jar;
          ports:
            - containerPort: 6382
          imagePullPolicy: Always
      restartPolicy: Always
