apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-microservice
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: user-microservice
          image: ameniawy/ultimate-team-user
          env:
            - name: RABBIT_MQ_PORT
              value: "5672"
          args:
            - bash
            - -c
            - sleep 10; java -jar user-0.0.1-SNAPSHOT-jar-with-dependencies.jar;
          ports:
            - containerPort: 6381
          imagePullPolicy: Always
      restartPolicy: Always
